//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs425
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public long VIN { get; set; }
        public long License_num { get; set; }
        public System.DateTime day_of_rental { get; set; }
        public int rented_days { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
